#\u914D\u7F6E\u9879\u76EE\u7AEF\u53E3\u53F7
server:
  port: 8080
#\u914D\u7F6E\u6570\u636E\u6E90
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///baizhanfarm
    username: root
    password: 123456
  #\u6A21\u5757\u540D
  application:
    name:
      farm_main

#\u914D\u7F6E\u65E5\u5FD7
logging:
  pattern:
    console:
#\u914D\u7F6Emybatis-plus
mybatis-plus:
  configuration:
    #sql\u65E5\u5FD7\u6253\u5370
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #\u5F00\u542F\u5217\u540D\u81EA\u52A8\u9A7C\u5CF0\u547D\u540D\u6620\u5C04\u89C4\u5219
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      #id\u81EA\u589E
      id-type: auto